export const CATEGORIES = [
  "머리",
  "옷",
  "눈",
  "귀",
  "턱",
  "배경",
  "펫",
  "소품",
] as const;

export type Category = (typeof CATEGORIES)[number];

export const MOCK_ITEMS = [
  {
    id: 1,
    name: "웨폰퍼프 - I 링",
    level: 3,
    price: 333333,
    averagePrice: 333333,
    timeLeft: "23시간 58분",
    isNew: true,
    category: "소품",
    image: "/placeholder-ring.png",
  },
  {
    id: 2,
    name: "봄 바람 운동화",
    level: 0,
    price: 29999999,
    averagePrice: 29999999,
    timeLeft: "47시간 58분",
    isNew: true,
    category: "옷",
    image: "/placeholder-shoes.png",
  },
  {
    id: 3,
    name: "무스펠 로그슈즈",
    level: 0,
    price: 172222222,
    averagePrice: 172222222,
    timeLeft: "47시간 58분",
    isNew: true,
    category: "옷",
    image: "/placeholder-shoes2.png",
  },
  {
    id: 4,
    name: "스노우 쿠키 부츠",
    level: 0,
    price: 277777777,
    averagePrice: 277777777,
    timeLeft: "23시간 58분",
    isNew: false,
    category: "옷",
    image: "/placeholder-boots.png",
  },
  {
    id: 5,
    name: "영원한 환생의 불꽃",
    level: 6,
    price: 34200000,
    perItemPrice: 5700000,
    count: 6,
    timeLeft: "47시간 58분",
    isNew: false,
    category: "소품",
    image: "/placeholder-fire.png",
  },
  {
    id: 6,
    name: "거울세계의 코어 젬스톤",
    level: 1,
    price: 1000000,
    perItemPrice: 1000000,
    count: 1,
    timeLeft: "47시간 58분",
    isNew: false,
    category: "소품",
    image: "/placeholder-gem.png",
  },
  {
    id: 7,
    name: "아케인셰이드 소울슈터",
    level: 0,
    price: 2999999999,
    averagePrice: 2999999999,
    timeLeft: "47시간 58분",
    isNew: true,
    category: "무기", // Note: '무기' isn't in main list but in screenshot
    image: "/placeholder-weapon.png",
  },
];
